### ISSUE TITLE
open_vins on runoff issue on zed2

### ISSUE THREAD

**Issue by truncs** [rpng/open_vins#157]
Hi,

I am trying to run open_vins using zed2 cameras and testing it on a bag results in very unstable results (lot of bias in the trajectory and can't detect stop velocity). I am attaching the screenshot and the config files that I use 

![openvins](https://user-images.githubusercontent.com/157234/114213563-f645d000-9917-11eb-8ca1-5f2103c3b7b2.png)

```
<launch>

    <node name="run_serial_msckf" pkg="ov_msckf" type="run_serial_msckf" output="screen">
    
        <!-- bag topics -->
        <param name="topic_imu"      type="string" value="/zed2/zed_node/imu/data_raw" />
        <param name="topic_camera0"  type="string" value="/zed2/zed_node/left_raw/image_raw_color" />
        <param name="topic_camera1"  type="string" value="/zed2/zed_node/right_raw/image_raw_color" />
        <rosparam param="stereo_pairs">[0,1]</rosparam>
    
        <!-- bag parameters -->
        <param name="path_bag"    type="string" value="/root/data/zed_20210319104926.bag" />
        <param name="bag_start"   type="int"    value="0" />
        <param name="bag_durr"    type="int"    value="-1" />
    

	<!-- world/filter parameters -->
        <param name="use_fej"                type="bool"   value="true" />
        <param name="use_imuavg"             type="bool"   value="true" />
        <param name="use_rk4int"             type="bool"   value="true" />
        <param name="use_stereo"             type="bool"   value="true" />
        <param name="calib_cam_extrinsics"   type="bool"   value="true" />
        <param name="calib_cam_intrinsics"   type="bool"   value="true" />
        <param name="calib_cam_timeoffset"   type="bool"   value="true" />
        <param name="calib_camimu_dt"        type="double" value="0.017971296601266912" />
        <param name="max_clones"             type="int"    value="11" />
        <param name="max_slam"               type="int"    value="75" />
        <param name="max_slam_in_update"     type="int"    value="25" /> <!-- 25 seems to work well -->
        <param name="max_msckf_in_update"    type="int"    value="40" />
        <param name="max_cameras"            type="int"    value="2" />
        <param name="dt_slam_delay"          type="double" value="3" />

        <param name="init_window_time"       type="double" value="0.5" />
        <param name="init_imu_thresh"        type="double" value="0.1" />
        <rosparam param="gravity">[0.0,0.0,9.81]</rosparam>
        <param name="feat_rep_msckf"         type="string" value="GLOBAL_3D" />
        <param name="feat_rep_slam"          type="string" value="GLOBAL_3D" />

	<!-- zero velocity update parameters -->
        <param name="try_zupt"               type="bool"   value="false" />
        <param name="zupt_chi2_multipler"    type="int"    value="2" />
/        <param name="zupt_max_velocity"      type="double" value="0.3" />
        <param name="zupt_noise_multiplier"  type="double" value="50" />
		 
        <!-- tracker/extractor parameters -->
        <param name="use_klt"          type="bool"   value="true" />
        <param name="fast_threshold"   type="int"    value="10" />
        <param name="grid_x"           type="int"    value="5" />
        <param name="grid_y"           type="int"    value="3" />
        <param name="min_px_dist"      type="int"    value="10" />
        <param name="num_pts"          type="int"    value="400" />
    
        <!-- sensor noise values / update -->
        <param name="up_msckf_sigma_px"            type="double"   value="5" />
        <param name="up_msckf_chi2_multipler"      type="double"   value="1" />
        <param name="gyroscope_noise_density"      type="double"   value="0.0002" />
        <param name="gyroscope_random_walk"        type="double"   value="" />
        <param name="accelerometer_noise_density"  type="double"   value="0.02" />
        <param name="accelerometer_random_walk"    type="double"   value="8.0e-05" />
    
        <!-- camera intrinsics -->
	<rosparam param="cam0_wh">[1280, 720]</rosparam>
        <rosparam param="cam1_wh">[1280, 720]</rosparam>
        <param name="cam0_is_fisheye" type="bool" value="false" />
        <param name="cam1_is_fisheye" type="bool" value="false" />
        <rosparam param="cam0_k">[570.3923333887533,571.7991908377907,658.6866577567074,357.00582773085546]</rosparam>
        <rosparam param="cam0_d">[-0.0862203774707283,0.07813956149147104,-0.0006706897894738282,0.0005174826758427107]</rosparam>
        <rosparam param="cam1_k">[573.5060545651859,574.7946327267398,658.0083966321519,355.7981104109921]</rosparam>
        <rosparam param="cam1_d">[-0.08322421471198302,0.0736502021044247,-0.0011325348405781517,0.00029983051060706396]</rosparam>
    
        <!-- camera extrinsics -->
        <rosparam param="T_C0toI">
            [
0.00916668776984686, -0.9999508579504861, 0.003775383347028649, -0.10031401932563686,
        0.000799258388630264, -0.0037682139625440647, -0.9999925808472585, 0.005421274724173588,
        0.9999576656145792, 0.009169637267600617, 0.0007646770705903583, 0.040830056141113125,
            0.0, 0.0, 0.0, 1.0
            ]
        </rosparam>
        <rosparam param="T_C1toI">
            [
        0.9999762529203078, 0.0011037407708745298, 0.006802598898783178, -0.11911122223386701,
        -0.0011213192339498321, 0.9999960410276351, 0.0025808084466722885, 0.00015343654353025578,
        -0.006799723423977697, -0.0025883750449944786, 0.9999735316877093, 0.001018077864795099,
            0.0, 0.0, 0.0, 1.0
            ]
        </rosparam>
    
    </node>

    <node type="rviz" name="rviz" pkg="rviz" args="-d $(find ov_msckf)/launch/display.rviz" />

</launch>
```

The configuration was done using Kalibr and here's my config file

```
cam0:
  T_cam_imu:
  - [0.0023661383021121862, -0.9999852376642965, 0.004891405014821881, 0.018520139160040982]
  - [-0.001778892596313919, -0.004895620035355042, -0.9999864341307854, 0.005185516233583466]
  - [0.9999956184557357, 0.0023574049192230384, -0.0017904500497825104, 0.03995238963352001]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [-0.0862203774707283, 0.07813956149147104, -0.0006706897894738282,
    0.0005174826758427107]
  distortion_model: radtan
  intrinsics: [570.3923333887533, 571.7991908377907, 658.6866577567074, 357.00582773085546]
  resolution: [1280, 720]
  rostopic: /zed2/zed_node/left_raw/image_raw_color
  timeshift_cam_imu: 0.017971296601266912
cam1:
  T_cam_imu:
  - [0.00916668776984686, -0.9999508579504861, 0.003775383347028649, -0.10031401932563686]
  - [0.000799258388630264, -0.0037682139625440647, -0.9999925808472585, 0.005421274724173588]
  - [0.9999576656145792, 0.009169637267600617, 0.0007646770705903583, 0.040830056141113125]
  - [0.0, 0.0, 0.0, 1.0]
  T_cn_cnm1:
  - [0.9999762529203078, 0.0011037407708745298, 0.006802598898783178, -0.11911122223386701]
  - [-0.0011213192339498321, 0.9999960410276351, 0.0025808084466722885, 0.00015343654353025578]
  - [-0.006799723423977697, -0.0025883750449944786, 0.9999735316877093, 0.001018077864795099]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [-0.08322421471198302, 0.0736502021044247, -0.0011325348405781517,
    0.00029983051060706396]
  distortion_model: radtan
  intrinsics: [573.5060545651859, 574.7946327267398, 658.0083966321519, 355.7981104109921]
  resolution: [1280, 720]
  rostopic: /zed2/zed_node/right_raw/image_raw_color
  timeshift_cam_imu: 0.017919297596632126
```

I also had tried using the same dataset with s-msckf which seems to work fine. Attaching the config file that I use for s-msckf as well

```
<launch>

  <arg name="robot" default="zed"/>
  <arg name="fixed_frame_id" default="base_link"/>
  <arg name="calibration_file"
    default="$(find msckf_vio)/config/camchain-imucam-zed.yaml"/>

  <!-- Image Processor Nodelet  -->
  <include file="$(find msckf_vio)/launch/image_processor_zed.launch">
    <arg name="robot" value="$(arg robot)"/>
    <arg name="calibration_file" value="$(arg calibration_file)"/>
  </include>

  <!-- Msckf Vio Nodelet  -->
  <group ns="$(arg robot)">
    <node pkg="nodelet" type="nodelet" name="vio"
      args='standalone msckf_vio/MsckfVioNodelet'
      output="screen">

      <!-- Calibration parameters -->
      <rosparam command="load" file="$(arg calibration_file)"/>

      <param name="publish_tf" value="true"/>
      <param name="frame_rate" value="15"/>
      <param name="fixed_frame_id" value="$(arg fixed_frame_id)"/>
      <param name="child_frame_id" value="odom"/>
      <param name="max_cam_state_size" value="15"/>
      <param name="position_std_threshold" value="8.0"/>

      <param name="rotation_threshold" value="0.2618"/>
      <param name="translation_threshold" value="0.4"/>
      <param name="tracking_rate_threshold" value="0.5"/>

      <!-- Feature optimization config -->
      <param name="feature/config/translation_threshold" value="-1.0"/>

      <!-- These values should be standard deviation -->
      <param name="noise/gyro" value="0.005"/>
      <param name="noise/acc" value="0.5"/>
      <param name="noise/gyro_bias" value="0.001"/>
      <param name="noise/acc_bias" value="0.1"/>
      <param name="noise/feature" value="0.035"/>

      <param name="initial_state/velocity/x" value="0.0"/>
      <param name="initial_state/velocity/y" value="0.0"/>
      <param name="initial_state/velocity/z" value="0.0"/>

      <!-- These values should be covariance -->
      <param name="initial_covariance/velocity" value="0.25"/>
      <param name="initial_covariance/gyro_bias" value="0.01"/>
      <param name="initial_covariance/acc_bias" value="0.01"/>
      <param name="initial_covariance/extrinsic_rotation_cov" value="3.0462e-4"/>
      <param name="initial_covariance/extrinsic_translation_cov" value="2.5e-5"/>

      <remap from="~imu" to="/zed2/zed_node/imu/data_raw"/>
      <remap from="~features" to="image_processor/features"/>

    </node>
  </group>

</launch>
```

I am wondering if there are any thoughts about what could be going wrong or how to go about debugging this?

Thanks!
