### ISSUE TITLE
The tracking path keeps moving on RViz.

### ISSUE THREAD

**Issue by oguzhanbzglu** [rpng/open_vins#391]
Hello all,

Everything looks good on OpenVins but when I wanted to see on Rviz I got that (below pic). The path is keeps moving after I run the `subscribe.launch`.

Here is the camera what I use:

```
Device info: 
    Name                          : 	Intel RealSense D455
    Serial Number                 : 	151422254150
    Firmware Version              : 	5.12.7.150
    Recommended Firmware Version  : 	5.15.1
    Physical Port                 : 	/sys/devices/pci0000:00/0000:00:14.0/usb1/1-3/1-3:1.0/video4linux/video2
    Debug Op Code                 : 	15
    Advanced Mode                 : 	YES
    Product Id                    : 	0B5C
    Camera Locked                 : 	YES
    Usb Type Descriptor           : 	2.1
    Product Line                  : 	D400
    Asic Serial Number            : 	151223064077
    Firmware Update Id            : 	151223064077
```

Is someone really know what is the solution or what am I doing wrong? Thanks

![openvins](https://github.com/rpng/open_vins/assets/76758539/c8cb6513-25b5-4f42-9c80-633901f35aa8)

**Comment by goldbattle** [comment]
Likely your calibration parameters are wrong or the filter initialized incorrectly. Feel free to post a bag and all your config and launch files to enable debugging.

**Comment by sguttikon** [comment]
@goldbattle I am also facing the same issue. 
[rosbag link](https://cloud.dfki.de/owncloud/index.php/s/nnJqNLaLzftB9jb)

launch_d455.launch
```
<?xml version="1.0" encoding="UTF-8"?>
<launch>
  <arg name="serial_no"           default="135122250121"/>
  <arg name="json_file_path"      default=""/>
  <arg name="camera"              default="d455"/>
  <arg name="tf_prefix"           default="$(arg camera)"/>
  <arg name="external_manager"    default="false"/>
  <arg name="manager"             default="realsense2_camera_manager"/>
  <arg name="respawn"             default="true"/>

  <arg name="fisheye_width"       default="640"/>
  <arg name="fisheye_height"      default="480"/>
  <arg name="enable_fisheye"      default="false"/>

  <arg name="depth_width"         default="848"/>
  <arg name="depth_height"        default="480"/>
  <arg name="enable_depth"        default="true"/>

  <arg name="infra_width"        default="848"/>
  <arg name="infra_height"       default="480"/>
  <arg name="enable_infra1"       default="true"/>
  <arg name="enable_infra2"       default="true"/>

  <arg name="color_width"         default="848"/>
  <arg name="color_height"        default="480"/>
  <arg name="enable_color"        default="true"/>

  <arg name="fisheye_fps"         default="30"/>
  <arg name="depth_fps"           default="30"/>
  <arg name="infra_fps"           default="30"/>
  <arg name="color_fps"           default="30"/>
  <arg name="gyro_fps"            default="400"/>
  <arg name="accel_fps"           default="200"/>
  <arg name="enable_gyro"         default="true"/>
  <arg name="enable_accel"        default="true"/>

  <arg name="enable_pointcloud"         default="false"/>
  <arg name="pointcloud_texture_stream" default="RS2_STREAM_COLOR"/>
  <arg name="pointcloud_texture_index"  default="0"/>

  <arg name="enable_sync"               default="false"/>
  <arg name="align_depth"               default="true"/>

  <arg name="filters"                   default="pointcloud"/>
  <arg name="clip_distance"             default="-2"/>
  <arg name="linear_accel_cov"          default="0.01"/>
  <arg name="initial_reset"             default="true"/>
  <arg name="reconnect_timeout"         default="6.0"/>
  <arg name="unite_imu_method"          default="linear_interpolation"/>
  <arg name="topic_odom_in"             default="odom_in"/>
  <arg name="calib_odom_file"           default=""/>
  <arg name="publish_odom_tf"           default="true"/>
  <arg name="allow_no_texture_points"   default="false"/>

  <rosparam ns="$(arg camera)"> stereo_module/emitter_enabled: 0 </rosparam>

  <group ns="$(arg camera)">
    <include file="$(find realsense2_camera)/launch/includes/nodelet.launch.xml">
      <arg name="tf_prefix"                value="$(arg tf_prefix)"/>
      <arg name="external_manager"         value="$(arg external_manager)"/>
      <arg name="manager"                  value="$(arg manager)"/>
      <arg name="serial_no"                value="$(arg serial_no)"/>
      <arg name="json_file_path"           value="$(arg json_file_path)"/>
      <arg name="respawn"                  value="$(arg respawn)"/>

      <arg name="enable_pointcloud"        value="$(arg enable_pointcloud)"/>
      <arg name="pointcloud_texture_stream" value="$(arg pointcloud_texture_stream)"/>
      <arg name="pointcloud_texture_index"  value="$(arg pointcloud_texture_index)"/>
      <arg name="enable_sync"              value="$(arg enable_sync)"/>
      <arg name="align_depth"              value="$(arg align_depth)"/>

      <arg name="fisheye_width"            value="$(arg fisheye_width)"/>
      <arg name="fisheye_height"           value="$(arg fisheye_height)"/>
      <arg name="enable_fisheye"           value="$(arg enable_fisheye)"/>

      <arg name="depth_width"              value="$(arg depth_width)"/>
      <arg name="depth_height"             value="$(arg depth_height)"/>
      <arg name="enable_depth"             value="$(arg enable_depth)"/>

      <arg name="color_width"              value="$(arg color_width)"/>
      <arg name="color_height"             value="$(arg color_height)"/>
      <arg name="enable_color"             value="$(arg enable_color)"/>

      <arg name="infra_width"              value="$(arg infra_width)"/>
      <arg name="infra_height"             value="$(arg infra_height)"/>
      <arg name="enable_infra1"            value="$(arg enable_infra1)"/>
      <arg name="enable_infra2"            value="$(arg enable_infra2)"/>

      <arg name="fisheye_fps"              value="$(arg fisheye_fps)"/>
      <arg name="depth_fps"                value="$(arg depth_fps)"/>
      <arg name="infra_fps"                value="$(arg infra_fps)"/>
      <arg name="color_fps"                value="$(arg color_fps)"/>
      <arg name="gyro_fps"                 value="$(arg gyro_fps)"/>
      <arg name="accel_fps"                value="$(arg accel_fps)"/>
      <arg name="enable_gyro"              value="$(arg enable_gyro)"/>
      <arg name="enable_accel"             value="$(arg enable_accel)"/>

      <arg name="filters"                  value="$(arg filters)"/>
      <arg name="clip_distance"            value="$(arg clip_distance)"/>
      <arg name="linear_accel_cov"         value="$(arg linear_accel_cov)"/>
      <arg name="initial_reset"            value="$(arg initial_reset)"/>
      <arg name="reconnect_timeout"        value="$(arg reconnect_timeout)"/>
      <arg name="unite_imu_method"         value="$(arg unite_imu_method)"/>
      <arg name="topic_odom_in"            value="$(arg topic_odom_in)"/>
      <arg name="calib_odom_file"          value="$(arg calib_odom_file)"/>
      <arg name="publish_odom_tf"          value="$(arg publish_odom_tf)"/>
      <arg name="allow_no_texture_points"  value="$(arg allow_no_texture_points)"/>
    </include>
  </group>


</launch>
```

kalibr_imucam_chain.yaml
```
%YAML:1.0


cam0:
  T_cam_imu:
    - [0.9999817612353552, -0.00023273685338723267, -0.00603514955858592, 0.02910176881293301]
    - [0.00020926586156371987, 0.9999924144024931, -0.0038893888044284276, -0.003308029859133931]
    - [0.006036008982482416, 0.003888054916009367, 0.9999742244800782, -0.016912520625810057]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0.0017002394494499168, -0.0018209194956234284, 0.0007389866716620277, 0.0005987273042336999]
  distortion_model: radtan
  intrinsics: [429.4783460071125, 430.79666147375366, 429.14498450050763, 242.263552170896]
  resolution: [848, 480]
  rostopic: /d455/infra1/image_rect_raw
  timeshift_cam_imu: 0.004471019849534963

cam1:
  T_cam_imu:
    - [0.9999857502272286, -0.0007207600335991035, -0.005289598043443342, -0.06573577742351527]
    - [0.00070444882790488, 0.9999949937025124, -0.0030848536045250583, -0.003404401961071722]
    - [0.005291795001329591, 0.0030810833949203686, 0.9999812517396403, -0.017062501469330086]
    - [0.0, 0.0, 0.0, 1.0]
  T_cn_cnm1:
    - [0.9999996029852, -0.0004909183832207501, 0.0007436589148304757, -0.09482658150854983]
    - [0.0004903178442608461, 0.9999995537551436, 0.0008075134198832229, -9.69856073082385e-05]
    - [-0.0007440550061590289, -0.0008071484700524597, 0.9999993974465651, -0.00013100778868375246]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [0.0039470351616460895, -0.003996694514156234, 0.00048014252750379837, 0.00017671122823091826]
  distortion_model: radtan
  intrinsics: [429.3371770858414, 430.6077978789475, 429.0188576291719, 242.0044865872214]
  resolution: [848, 480]
  rostopic: /d455/infra2/image_rect_raw
  timeshift_cam_imu: 0.0044677872734078874
  ```
  
  kalibr_imu_chain.yaml
  ```%YAML:1.0
imu0:
  T_i_b:
    - [1.0, 0.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0, 0.0]
    - [0.0, 0.0, 1.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0]
  # Values from allan plots
  #accelerometer_noise_density: 0.0012267420396737515
  #accelerometer_random_walk: 8.642928373237232e-05
  #gyroscope_noise_density: 0.00013063264431612898
  #gyroscope_random_walk: 2.1210626575775937e-06
  # Inflated values (to account for unmodelled effects)
  #  - white noise multiplied by 5
  #  - bias random walk multiplied by 10
  accelerometer_noise_density: 0.00613371019
  accelerometer_random_walk: 0.00086429283
  gyroscope_noise_density: 0.00065316322
  gyroscope_random_walk: 2.121062e-05
  rostopic: /d455/imu
  time_offset: 0.0
  update_rate: 400
  # three different modes supported:
  # "calibrated" (same as "kalibr"), "kalibr", "rpng"
  model: "kalibr"
  # how to get from Kalibr imu.yaml result file:
  #   - Tw is imu0:gyroscopes:M:
  #   - R_IMUtoGYRO: is imu0:gyroscopes:C_gyro_i:
  #   - Ta is imu0:accelerometers:M:
  #   - R_IMUtoACC not used by Kalibr
  #   - Tg is imu0:gyroscopes:A:
  Tw:
    - [ 1.0, 0.0, 0.0 ]
    - [ 0.0, 1.0, 0.0 ]
    - [ 0.0, 0.0, 1.0 ]
  R_IMUtoGYRO:
    - [ 1.0, 0.0, 0.0 ]
    - [ 0.0, 1.0, 0.0 ]
    - [ 0.0, 0.0, 1.0 ]
  Ta:
    - [ 1.0, 0.0, 0.0 ]
    - [ 0.0, 1.0, 0.0 ]
    - [ 0.0, 0.0, 1.0 ]
  R_IMUtoACC:
    - [ 1.0, 0.0, 0.0 ]
    - [ 0.0, 1.0, 0.0 ]
    - [ 0.0, 0.0, 1.0 ]
  Tg:
    - [ 0.0, 0.0, 0.0 ]
    - [ 0.0, 0.0, 0.0 ]
    - [ 0.0, 0.0, 0.0 ]
    ```
