### ISSUE TITLE
CARLA Simulator: OpenVINS Execution Issue

### ISSUE THREAD

**Issue by hddandy123** [rpng/open_vins#508]
Experiment Environment

- Ubuntu 22.04, ROS 2 Humble, GPU RTX 3080

 CARLA Camera: Two RGB mono cameras mounted 3 cm to the left and right of the IMU at the rear-center of the vehicle (stereo configuration)
- Resolution: 800 × 600
- FOV: 90°
- Frequency: 20 Hz
- Noise: None
IMU Sensor: Mounted at the rear-center of the vehicle
- Frequency: 200 Hz
- Noise: None

config file
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
estimator_config
```
%YAML:1.0

verbosity: "DEBUG"
use_fej: true
integration: "discrete"
use_stereo: true
max_cameras: 2

calib_cam_extrinsics: false
calib_cam_intrinsics: false
calib_cam_timeoffset: false
calib_imu_intrinsics: false
calib_imu_g_sensitivity: false


max_clones: 20
max_slam: 50
max_slam_in_update: 50
max_msckf_in_update: 50
dt_slam_delay: 1

gravity_mag: 9.81

feat_rep_msckf: "ANCHORED_MSCKF_INVERSE_DEPTH"
feat_rep_slam: "ANCHORED_MSCKF_INVERSE_DEPTH"
feat_rep_aruco: "ANCHORED_MSCKF_INVERSE_DEPTH"

try_zupt: true
zupt_chi2_multipler: 1
zupt_max_velocity: 0.05
zupt_noise_multiplier: 20
zupt_max_disparity: 0.4
zupt_only_at_beginning: false

init_window_time: 4.0
init_imu_thresh: 0.5
init_max_disparity: 1.5
init_max_features: 75

init_dyn_use: false
init_dyn_mle_opt_calib: false
init_dyn_mle_max_iter: 50
init_dyn_mle_max_time: 0.05
init_dyn_mle_max_threads: 6
init_dyn_num_pose: 6
init_dyn_min_deg: 0.0

init_dyn_inflation_ori: 10
init_dyn_inflation_vel: 100
init_dyn_inflation_bg: 10
init_dyn_inflation_ba: 100
init_dyn_min_rec_cond: 1e-20

init_dyn_bias_g: [0.0, 0.0, 0.0]
init_dyn_bias_a: [0.0, 0.0, 0.0]

record_timing_information: false
record_timing_filepath: "/tmp/traj_timing.txt"

save_total_state: false
filepath_est: "/tmp/ov_estimate.txt"
filepath_std: "/tmp/ov_estimate_std.txt"
filepath_gt: "/tmp/ov_groundtruth.txt"

use_klt: true
num_pts: 200
fast_threshold: 20
grid_x: 8
grid_y: 6
min_px_dist: 10
knn_ratio: 0.65
track_frequency: 200.0
downsample_cameras: false
num_opencv_threads: 8
histogram_method: "HISTOGRAM"

fi_min_dist: 1.0
fi_max_dist: 300.0

use_aruco: false
num_aruco: 1024
downsize_aruco: true

up_msckf_sigma_px: 2
up_msckf_chi2_multipler: 1
up_slam_sigma_px: 2
up_slam_chi2_multipler: 1
up_aruco_sigma_px: 1
up_aruco_chi2_multipler: 1

use_mask: false

relative_config_imu: "kalibr_imu_chain.yaml"
relative_config_imucam: "kalibr_imucam_chain.yaml"
```
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
kalibr_imucam_chanin
```
%YAML:1.0

cam0:
  T_imu_cam: #rotation from camera to IMU R_CtoI, position of camera in IMU p_CinI
    - [1.0, 0.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0, 0.03]
    - [0.0, 0.0, 1.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0.0, 0.0, 0.0, 0.0]
  distortion_model: equidistant
  intrinsics: [400, 400, 400, 300] #fu, fv, cu, cv
  resolution: [800, 600]
  rostopic: /cam0/image_raw
  timeshift_cam_imu: 0

cam1:
  T_imu_cam: #rotation from camera to IMU R_CtoI, position of camera in IMU p_CinI
    - [1.0, 0.0, 0.0, 0.0]
    - [0.0, 1.0, 0.0, -0.03]
    - [0.0, 0.0, 1.0, 0.0]
    - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [0.0, 0.0, 0.0, 0.0]
  distortion_model: equidistant
  intrinsics: [400, 400, 400, 300] #fu, fv, cu, cv
  resolution: [800, 600]
  rostopic: /cam1/image_raw
  timeshift_cam_imu: 0
```
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ
kalibr_imu_chain
```
%YAML:1.0

imu0:
  T_i_b:
    - [ 0.1884594840352617, -0.49140043232876846, -0.8502991461740171, 0.0]
    - [-0.49140043232876846,  0.7024493785059616, -0.514869387071797, 0.0]
    - [ 0.8502991461740171,  0.514869387071797, -0.10909113745877685, 0.0]
    - [ 0.0,                  0.0,                0.0,                1.0]

  accelerometer_noise_density: 0  # [ m / s^2 / sqrt(Hz) ]   ( accel "white noise" )
  accelerometer_random_walk: 0   # [ m / s^3 / sqrt(Hz) ].  ( accel bias diffusion )
  gyroscope_noise_density: 0     # [ rad / s / sqrt(Hz) ]   ( gyro "white noise" )
  gyroscope_random_walk: 0        # [ rad / s^2 / sqrt(Hz) ] ( gyro bias diffusion )
  rostopic: /imu0
  time_offset: 0.0
  update_rate: 200.0
  # three different modes supported:
  # "calibrated" (same as "kalibr"), "kalibr", "rpng"
  model: "kalibr"
  # how to get from Kalibr imu.yaml result file:
  #   - Tw is imu0:gyroscopes:M:
  #   - R_IMUtoGYRO: is imu0:gyroscopes:C_gyro_i:
  #   - Ta is imu0:accelerometers:M:
  #   - R_IMUtoACC not used by Kalibr
  #   - Tg is imu0:gyroscopes:A:
  Tw:
    - [ 1.0, 0.0, 0.0 ]
    - [ 0.0, 1.0, 0.0 ]
    - [ 0.0, 0.0, 1.0 ]
  R_IMUtoGYRO:
    - [ 1.0, 0.0, 0.0 ]
    - [ 0.0, 1.0, 0.0 ]
    - [ 0.0, 0.0, 1.0 ]
  Ta:
    - [ 1.0, 0.0, 0.0 ]
    - [ 0.0, 1.0, 0.0 ]
    - [ 0.0, 0.0, 1.0 ]
  R_IMUtoACC:
    - [ 1.0, 0.0, 0.0 ]
    - [ 0.0, 1.0, 0.0 ]
    - [ 0.0, 0.0, 1.0 ]
  Tg:
    - [ 0.0, 0.0, 0.0 ]
    - [ 0.0, 0.0, 0.0 ]
    - [ 0.0, 0.0, 0.0 ]
```
ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

Problem Summary
When using CARLA-generated driving data as input to OpenVINS, the state estimation does not work correctly. Although it appears to run normally for the first 3–4 seconds, it repeatedly fails in the same segment thereafter. Moreover, whenever the estimated trajectory shakes or makes a sharp turn, the /ov_msckf/points_msckf topic appears and disappears intermittently.

Questions

1. Has anyone tried using CARLA simulator driving data as input to OpenVINS? If so, what precautions or special considerations are necessary?

2. Should the IMU‐to‐camera coordinate alignment be performed manually, or does OpenVINS automatically determine it at initialization?

3. In the TrackHist topic video, feature detection appears to be poor. What might cause this issue (e.g., camera calibration, lighting conditions, motion blur, etc.)?

4. Is there a known issue in which the /ov_msckf/points_msckf topic appears and disappears whenever the estimated trajectory becomes unstable?

5. Why might OpenVINS work normally for only the first few seconds and then consistently fail in the same segment (for example, due to mapping errors, timestamp synchronization issues, etc.)?

6. During straight sections, CARLA tends to output longitudinal linear acceleration values that are almost zero. Could such near‐zero acceleration cause the estimation to fail?

If you have any other potential issues beyond the above, please feel free to add them. Thank you for reviewing and providing advice. If you need any additional configuration files, log files, or captured images, please let me know at any time.

![Image](https://github.com/user-attachments/assets/7f5690da-f957-4d6c-8322-1ff875012156)
![Image](https://github.com/user-attachments/assets/24770edf-224b-4ec2-b504-03424d1fb893)
https://www.dropbox.com/scl/fi/hzb7hjpk1crldwev1t2ja/data_driving.zip?rlkey=fdi3axw1iro3cbho6rn3wqmex&st=8877dgu3&dl=0
