### ISSUE TITLE
openVINS vs VINS fusion 

### ISSUE THREAD

**Issue by moshanATucsd** [rpng/open_vins#65]
Hi, 

I have collected a dataset using a ground robot with some very noisy IMU data that looks like below. I tried to use openVINS and it could not produce an accurate estimate, and the trajectory drifts away fairly quickly. On the other hand, I also tried [VINS fusion](https://github.com/HKUST-Aerial-Robotics/VINS-Fusion) on the same dataset and it works reasonably. 

I am wondering whether you could kindly provide some suggestions regarding how to make openVINS work on my noisy dataset? I think this issue might be due to the robust state initialization that VINS fusion has, but I am not sure about that. Is there any advice as to the reasons why VINS fusion could work on this dataset while openVINS could not?

```
header: 
  seq: 6158
  stamp: 
    secs: 62
    nsecs: 840000000
  frame_id: "husky/imu"
orientation: 
  x: -0.00778974127024
  y: 0.0148112457246
  z: -0.938592493534
  w: -0.344621777534
orientation_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
angular_velocity: 
  x: 0.0706935450435
  y: 0.00419082771987
  z: 0.00554124312475
angular_velocity_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
linear_acceleration: 
  x: 0.0379937924445
  y: -1.61441624165
  z: 13.8011989594
linear_acceleration_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
---
header: 
  seq: 6159
  stamp: 
    secs: 62
    nsecs: 850000000
  frame_id: "husky/imu"
orientation: 
  x: -0.00787524413317
  y: 0.0145736578852
  z: -0.938595414162
  w: -0.344621837139
orientation_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
angular_velocity: 
  x: 0.0505583956838
  y: -0.000979542965069
  z: -0.000965483661275
angular_velocity_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
linear_acceleration: 
  x: 0.113806329668
  y: -0.189101085067
  z: 4.91889381409
linear_acceleration_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
---
header: 
  seq: 6160
  stamp: 
    secs: 62
    nsecs: 860000000
  frame_id: "husky/imu"
orientation: 
  x: -0.00749612553045
  y: 0.0146980192512
  z: -0.938594460487
  w: -0.344627857208
orientation_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
angular_velocity: 
  x: -0.00876136310399
  y: 0.03534899652
  z: -0.011736607179
angular_velocity_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
linear_acceleration: 
  x: 0.9152161479
  y: 0.579055964947
  z: 16.1999721527
linear_acceleration_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
---
header: 
  seq: 6161
  stamp: 
    secs: 62
    nsecs: 870000000
  frame_id: "husky/imu"
orientation: 
  x: -0.00738301966339
  y: 0.0146497953683
  z: -0.938593685627
  w: -0.344634324312
orientation_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
angular_velocity: 
  x: 0.00174215983134
  y: 0.024276426062
  z: -0.00156422634609
angular_velocity_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
linear_acceleration: 
  x: 0.178388744593
  y: 0.0271951276809
  z: 4.88155508041
linear_acceleration_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
---
header: 
  seq: 6162
  stamp: 
    secs: 62
    nsecs: 880000000
  frame_id: "husky/imu"
orientation: 
  x: -0.00807649828494
  y: 0.0140346186236
  z: -0.938595592976
  w: -0.344639092684
orientation_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
angular_velocity: 
  x: 0.139958277345
  y: -0.0703760534525
  z: 0.00606694724411
angular_velocity_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
linear_acceleration: 
  x: -1.70400393009
  y: -2.78002977371
  z: 8.72135257721
linear_acceleration_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
---
header: 
  seq: 6163
  stamp: 
    secs: 62
    nsecs: 890000000
  frame_id: "husky/imu"
orientation: 
  x: -0.00686156284064
  y: 0.0149453571066
  z: -0.938592970371
  w: -0.344634383917
orientation_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
angular_velocity: 
  x: -0.181113615632
  y: 0.113962888718
  z: -0.0206028353423
angular_velocity_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
linear_acceleration: 
  x: 3.57074141502
  y: 5.17043924332
  z: 12.3236408234
linear_acceleration_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
---
header: 
  seq: 6164
  stamp: 
    secs: 62
    nsecs: 900000000
  frame_id: "husky/imu"
orientation: 
  x: -0.00793886743486
  y: 0.0141544155777
  z: -0.938591957092
  w: -0.344647437334
orientation_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
angular_velocity: 
  x: 0.148331344128
  y: -0.0899239331484
  z: 0.0205429010093
angular_velocity_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
linear_acceleration: 
  x: -3.05314922333
  y: -5.02658462524
  z: 12.0337715149
linear_acceleration_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
---
header: 
  seq: 6165
  stamp: 
    secs: 62
    nsecs: 910000000
  frame_id: "husky/imu"
orientation: 
  x: -0.0077565992251
  y: 0.014366905205
  z: -0.938593924046
  w: -0.344637393951
orientation_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
angular_velocity: 
  x: -0.0408048927784
  y: 0.0103695737198
  z: -0.00154680665582
angular_velocity_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
linear_acceleration: 
  x: 1.57226002216
  y: 2.27591443062
  z: 8.40149402618
linear_acceleration_covariance: [0.1, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.1]
```
